version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./wait-for-it.sh:/wait-for-it.sh  # 추가
    command:
        sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=seopftware
      - DB_PASSWORD=password123
    depends_on:
      - db

  db: # postersql
    image: postgres:17-alpine
    volumes:
      - ./data/db:/var/lib/postgresq/dat
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=seopftware
      - POSTGRES_PASSWORD=password123
