# github actions ci/cd

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login in to Docker Hub
      - name: docker/login-action@v1
      - with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{serrets.DOCKERHUB_TOKEN}}

      - name: Check out - pull repository Code
        uses: actions/Checkout@v2

      - name: Run Test Code
        run: docker-compose run --rm app sh -c 'python manage.py test'
        
      - name: Run Flake8 for LINT Check
